name: Palette

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        run: |
          curl -o /tmp/palette.json https://raw.githubusercontent.com/catppuccin/palette/main/palette.json
          python -c "import json
          data = json.load(open('/tmp/palette.json'))

          for flavour in data:
            with open('lua/catppuccin/palettes/{flavour}.lua'.format(flavour = flavour), 'w') as f:
              f.write('return {\n')
              for accent in data[flavour]: f.write('\t{accent} = \"{hex}\",\n'.format(accent = accent, hex = data[flavour][accent]['hex']))
              f.write('}\n')"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'feat: auto-sync upstream palettes'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: new-palettes
          delete-branch: true
          title: 'feat: auto-sync upstream palettes'
          body: |
            Auto-update `lua/catppuccin/palettes/` based on https://github.com/catppuccin/palette/blob/main/palette.json
