name: Build
on:
  pull_request:
  push:
    branches: [main]
jobs:
  stylua:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check .
          version: 15.1

  selene:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always ./lua
          version: 0.24.0

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: none-ls.nvim
      - uses: actions/checkout@v2
        with:
          repository: nvim-lua/plenary.nvim
          path: none-ls.nvim/.tests/site/pack/deps/start/plenary.nvim
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: make test
        working-directory: none-ls.nvim
        timeout-minutes: 1
